import {
	AuditActionEnum,
	type AuditEventType,
	AuditTargetTypeEnum,
} from '@/entities/audit-event';

export const MOCK_AUDIT_EVENTS: AuditEventType[] = [
	{
		id: 'evt-001',
		action: AuditActionEnum.SERVICE_CREATED,
		actorId: 'usr-anna-ivanova',
		targetType: AuditTargetTypeEnum.SERVICE,
		targetId: 'svc-orders-worker',
		targetLabel: 'orders-worker',
		createdAt: '2026-05-03T10:42:00Z',
	},
	{
		id: 'evt-002',
		action: AuditActionEnum.TEMPLATE_USED,
		actorId: 'usr-anna-ivanova',
		targetType: AuditTargetTypeEnum.TEMPLATE,
		targetId: 'tpl-go-worker',
		targetLabel: 'Go Worker',
		createdAt: '2026-05-03T10:39:00Z',
		payload: { newServiceId: 'svc-orders-worker' },
	},
	{
		id: 'evt-003',
		action: AuditActionEnum.ROLE_CHANGED,
		actorId: 'usr-alexey-zaytsev',
		targetType: AuditTargetTypeEnum.USER,
		targetId: 'usr-mikhail-orlov',
		targetLabel: 'Михаил Орлов',
		createdAt: '2026-05-03T09:55:00Z',
		payload: { from: 'member', to: 'devops' },
	},
	{
		id: 'evt-004',
		action: AuditActionEnum.SERVICE_UPDATED,
		actorId: 'usr-denis-kravtsov',
		targetType: AuditTargetTypeEnum.SERVICE,
		targetId: 'svc-payments-api',
		targetLabel: 'payments-api',
		createdAt: '2026-05-03T09:14:00Z',
		payload: { fields: 'pipelineUrl, docsUrl' },
	},
	{
		id: 'evt-005',
		action: AuditActionEnum.TEAM_MEMBER_ADDED,
		actorId: 'usr-anna-ivanova',
		targetType: AuditTargetTypeEnum.TEAM,
		targetId: 'team-platform',
		targetLabel: 'Platform',
		createdAt: '2026-05-02T16:30:00Z',
		payload: { userId: 'usr-pavel-sidorov' },
	},
	{
		id: 'evt-006',
		action: AuditActionEnum.INTEGRATION_CONNECTED,
		actorId: 'usr-alexey-zaytsev',
		targetType: AuditTargetTypeEnum.INTEGRATION,
		targetId: 'int-datadog',
		targetLabel: 'Datadog',
		createdAt: '2026-05-02T14:20:00Z',
	},
	{
		id: 'evt-007',
		action: AuditActionEnum.SERVICE_DELETED,
		actorId: 'usr-roman-volkov',
		targetType: AuditTargetTypeEnum.SERVICE,
		targetId: 'svc-legacy-checkout',
		targetLabel: 'legacy-checkout',
		createdAt: '2026-05-02T11:05:00Z',
	},
	{
		id: 'evt-008',
		action: AuditActionEnum.TEMPLATE_USED,
		actorId: 'usr-ekaterina-belova',
		targetType: AuditTargetTypeEnum.TEMPLATE,
		targetId: 'tpl-nodejs-service',
		targetLabel: 'Node.js Service',
		createdAt: '2026-05-02T09:48:00Z',
		payload: { newServiceId: 'svc-promo-api' },
	},
	{
		id: 'evt-009',
		action: AuditActionEnum.SERVICE_CREATED,
		actorId: 'usr-ekaterina-belova',
		targetType: AuditTargetTypeEnum.SERVICE,
		targetId: 'svc-promo-api',
		targetLabel: 'promo-api',
		createdAt: '2026-05-02T09:50:00Z',
	},
	{
		id: 'evt-010',
		action: AuditActionEnum.ROLE_CHANGED,
		actorId: 'usr-alexey-zaytsev',
		targetType: AuditTargetTypeEnum.USER,
		targetId: 'usr-irina-fedorova',
		targetLabel: 'Ирина Фёдорова',
		createdAt: '2026-05-01T18:15:00Z',
		payload: { from: 'member', to: 'qa' },
	},
	{
		id: 'evt-011',
		action: AuditActionEnum.TEAM_MEMBER_REMOVED,
		actorId: 'usr-roman-volkov',
		targetType: AuditTargetTypeEnum.TEAM,
		targetId: 'team-commerce',
		targetLabel: 'Commerce',
		createdAt: '2026-05-01T15:42:00Z',
		payload: { userId: 'usr-natalia-popova' },
	},
	{
		id: 'evt-012',
		action: AuditActionEnum.SERVICE_UPDATED,
		actorId: 'usr-anna-ivanova',
		targetType: AuditTargetTypeEnum.SERVICE,
		targetId: 'svc-auth-service',
		targetLabel: 'auth-service',
		createdAt: '2026-05-01T13:08:00Z',
		payload: { fields: 'tags' },
	},
	{
		id: 'evt-013',
		action: AuditActionEnum.INTEGRATION_DISCONNECTED,
		actorId: 'usr-denis-kravtsov',
		targetType: AuditTargetTypeEnum.INTEGRATION,
		targetId: 'int-sonarqube',
		targetLabel: 'SonarQube',
		createdAt: '2026-05-01T11:55:00Z',
	},
	{
		id: 'evt-014',
		action: AuditActionEnum.SERVICE_CREATED,
		actorId: 'usr-roman-volkov',
		targetType: AuditTargetTypeEnum.SERVICE,
		targetId: 'svc-analytics-pipeline',
		targetLabel: 'analytics-pipeline',
		createdAt: '2026-04-30T14:25:00Z',
	},
	{
		id: 'evt-015',
		action: AuditActionEnum.TEMPLATE_USED,
		actorId: 'usr-roman-volkov',
		targetType: AuditTargetTypeEnum.TEMPLATE,
		targetId: 'tpl-rust-grpc',
		targetLabel: 'Rust gRPC Service',
		createdAt: '2026-04-30T10:32:00Z',
		payload: { newServiceId: 'svc-rates-grpc' },
	},
	{
		id: 'evt-016',
		action: AuditActionEnum.SERVICE_CREATED,
		actorId: 'usr-roman-volkov',
		targetType: AuditTargetTypeEnum.SERVICE,
		targetId: 'svc-rates-grpc',
		targetLabel: 'rates-grpc',
		createdAt: '2026-04-30T10:35:00Z',
	},
	{
		id: 'evt-017',
		action: AuditActionEnum.ROLE_CHANGED,
		actorId: 'usr-alexey-zaytsev',
		targetType: AuditTargetTypeEnum.USER,
		targetId: 'usr-pavel-sidorov',
		targetLabel: 'Павел Сидоров',
		createdAt: '2026-04-29T17:00:00Z',
		payload: { from: 'qa', to: 'member' },
	},
	{
		id: 'evt-018',
		action: AuditActionEnum.SERVICE_UPDATED,
		actorId: 'usr-olga-petrova',
		targetType: AuditTargetTypeEnum.SERVICE,
		targetId: 'svc-billing-gateway',
		targetLabel: 'billing-gateway',
		createdAt: '2026-04-29T12:18:00Z',
		payload: { fields: 'docsUrl' },
	},
	{
		id: 'evt-019',
		action: AuditActionEnum.TEAM_MEMBER_ADDED,
		actorId: 'usr-irina-fedorova',
		targetType: AuditTargetTypeEnum.TEAM,
		targetId: 'team-growth',
		targetLabel: 'Growth',
		createdAt: '2026-04-29T09:40:00Z',
		payload: { userId: 'usr-natalia-popova' },
	},
	{
		id: 'evt-020',
		action: AuditActionEnum.SERVICE_DELETED,
		actorId: 'usr-anna-ivanova',
		targetType: AuditTargetTypeEnum.SERVICE,
		targetId: 'svc-trial-api',
		targetLabel: 'trial-api',
		createdAt: '2026-04-28T16:05:00Z',
	},
	{
		id: 'evt-021',
		action: AuditActionEnum.INTEGRATION_CONNECTED,
		actorId: 'usr-denis-kravtsov',
		targetType: AuditTargetTypeEnum.INTEGRATION,
		targetId: 'int-slack',
		targetLabel: 'Slack',
		createdAt: '2026-04-28T11:32:00Z',
	},
	{
		id: 'evt-022',
		action: AuditActionEnum.SERVICE_CREATED,
		actorId: 'usr-mikhail-orlov',
		targetType: AuditTargetTypeEnum.SERVICE,
		targetId: 'svc-search-api',
		targetLabel: 'search-api',
		createdAt: '2026-04-27T14:55:00Z',
	},
	{
		id: 'evt-023',
		action: AuditActionEnum.TEMPLATE_USED,
		actorId: 'usr-mikhail-orlov',
		targetType: AuditTargetTypeEnum.TEMPLATE,
		targetId: 'tpl-go-worker',
		targetLabel: 'Go Worker',
		createdAt: '2026-04-27T14:50:00Z',
		payload: { newServiceId: 'svc-search-api' },
	},
	{
		id: 'evt-024',
		action: AuditActionEnum.SERVICE_UPDATED,
		actorId: 'usr-anna-ivanova',
		targetType: AuditTargetTypeEnum.SERVICE,
		targetId: 'svc-orders-worker',
		targetLabel: 'orders-worker',
		createdAt: '2026-04-26T09:18:00Z',
		payload: { fields: 'pipelineUrl' },
	},
	{
		id: 'evt-025',
		action: AuditActionEnum.ROLE_CHANGED,
		actorId: 'usr-alexey-zaytsev',
		targetType: AuditTargetTypeEnum.USER,
		targetId: 'usr-ekaterina-belova',
		targetLabel: 'Екатерина Белова',
		createdAt: '2026-04-25T16:42:00Z',
		payload: { from: 'member', to: 'manager' },
	},
	{
		id: 'evt-026',
		action: AuditActionEnum.TEAM_MEMBER_ADDED,
		actorId: 'usr-roman-volkov',
		targetType: AuditTargetTypeEnum.TEAM,
		targetId: 'team-commerce',
		targetLabel: 'Commerce',
		createdAt: '2026-04-25T11:08:00Z',
		payload: { userId: 'usr-ekaterina-belova' },
	},
	{
		id: 'evt-027',
		action: AuditActionEnum.SERVICE_CREATED,
		actorId: 'usr-olga-petrova',
		targetType: AuditTargetTypeEnum.SERVICE,
		targetId: 'svc-billing-gateway',
		targetLabel: 'billing-gateway',
		createdAt: '2026-04-24T13:30:00Z',
	},
	{
		id: 'evt-028',
		action: AuditActionEnum.SERVICE_UPDATED,
		actorId: 'usr-roman-volkov',
		targetType: AuditTargetTypeEnum.SERVICE,
		targetId: 'svc-promo-api',
		targetLabel: 'promo-api',
		createdAt: '2026-04-23T15:14:00Z',
		payload: { fields: 'tags, docsUrl' },
	},
	{
		id: 'evt-029',
		action: AuditActionEnum.SERVICE_DELETED,
		actorId: 'usr-alexey-zaytsev',
		targetType: AuditTargetTypeEnum.SERVICE,
		targetId: 'svc-deprecated-feed',
		targetLabel: 'deprecated-feed',
		createdAt: '2026-04-23T10:00:00Z',
	},
	{
		id: 'evt-030',
		action: AuditActionEnum.INTEGRATION_CONNECTED,
		actorId: 'usr-denis-kravtsov',
		targetType: AuditTargetTypeEnum.INTEGRATION,
		targetId: 'int-github',
		targetLabel: 'GitHub',
		createdAt: '2026-04-22T08:48:00Z',
	},
];
