import {
	ServiceEnvironmentNameEnum,
	ServiceHealthEnum,
	type ServiceType,
} from '@/entities/service';

export const MOCK_SERVICES: ServiceType[] = [
	{
		id: 'svc-payments-api',
		projectId: 'proj-payments',
		ownerTeamId: 'team-platform',
		name: 'payments-api',
		slug: 'payments-api',
		description: 'Платёжный API для основного контура заказов',
		tags: ['api', 'payments', 'critical'],
		language: 'TypeScript',
		repoUrl: 'https://github.com/devgate/payments-api',
		pipelineUrl: 'https://ci.devgate.local/payments-api',
		docsUrl: 'https://docs.devgate.local/payments-api',
		environments: [
			{
				name: ServiceEnvironmentNameEnum.PROD,
				url: 'https://api.devgate.com/payments',
			},
			{ name: ServiceEnvironmentNameEnum.STAGE },
			{ name: ServiceEnvironmentNameEnum.DEV },
		],
		slo: { availability: 99.95, latencyP95Ms: 180 },
		health: ServiceHealthEnum.HEALTHY,
		dependencies: ['svc-auth-service', 'svc-billing-gateway'],
		createdAt: '2025-08-12T09:00:00Z',
		updatedAt: '2026-04-30T17:24:00Z',
	},
	{
		id: 'svc-orders-worker',
		projectId: 'proj-commerce',
		ownerTeamId: 'team-commerce',
		name: 'orders-worker',
		slug: 'orders-worker',
		description: 'Воркер обработки очереди заказов из Kafka',
		tags: ['worker', 'kafka', 'orders'],
		language: 'Go',
		repoUrl: 'https://github.com/devgate/orders-worker',
		pipelineUrl: 'https://ci.devgate.local/orders-worker',
		environments: [
			{ name: ServiceEnvironmentNameEnum.PROD },
			{ name: ServiceEnvironmentNameEnum.STAGE },
		],
		slo: { availability: 99.9 },
		health: ServiceHealthEnum.HEALTHY,
		dependencies: ['svc-payments-api'],
		createdAt: '2025-09-01T11:30:00Z',
		updatedAt: '2026-05-01T08:12:00Z',
	},
	{
		id: 'svc-billing-gateway',
		projectId: 'proj-billing',
		ownerTeamId: 'team-billing',
		name: 'billing-gateway',
		slug: 'billing-gateway',
		description: 'Шлюз биллинга, агрегирует тарифы и подписки',
		tags: ['gateway', 'billing'],
		language: 'TypeScript',
		repoUrl: 'https://github.com/devgate/billing-gateway',
		pipelineUrl: 'https://ci.devgate.local/billing-gateway',
		environments: [
			{ name: ServiceEnvironmentNameEnum.PROD },
			{ name: ServiceEnvironmentNameEnum.STAGE },
		],
		slo: { availability: 99.5, latencyP95Ms: 420 },
		health: ServiceHealthEnum.DEGRADED,
		dependencies: ['svc-auth-service'],
		createdAt: '2025-07-15T10:00:00Z',
		updatedAt: '2026-05-02T16:00:00Z',
	},
	{
		id: 'svc-auth-service',
		projectId: 'proj-platform',
		ownerTeamId: 'team-platform',
		name: 'auth-service',
		slug: 'auth-service',
		description: 'Сервис аутентификации, выдаёт JWT и обновляет refresh-токены',
		tags: ['api', 'auth', 'critical'],
		language: 'Go',
		repoUrl: 'https://github.com/devgate/auth-service',
		pipelineUrl: 'https://ci.devgate.local/auth-service',
		docsUrl: 'https://docs.devgate.local/auth',
		environments: [
			{ name: ServiceEnvironmentNameEnum.PROD },
			{ name: ServiceEnvironmentNameEnum.STAGE },
			{ name: ServiceEnvironmentNameEnum.DEV },
		],
		slo: { availability: 99.99, latencyP95Ms: 90 },
		health: ServiceHealthEnum.HEALTHY,
		dependencies: [],
		createdAt: '2025-06-01T08:00:00Z',
		updatedAt: '2026-04-28T11:45:00Z',
	},
	{
		id: 'svc-notifications',
		projectId: 'proj-growth',
		ownerTeamId: 'team-growth',
		name: 'notifications',
		slug: 'notifications',
		description: 'Отправка email и push уведомлений',
		tags: ['worker', 'email', 'push'],
		language: 'Python',
		repoUrl: 'https://github.com/devgate/notifications',
		pipelineUrl: 'https://ci.devgate.local/notifications',
		environments: [
			{ name: ServiceEnvironmentNameEnum.PROD },
			{ name: ServiceEnvironmentNameEnum.STAGE },
		],
		slo: { availability: 99.5 },
		health: ServiceHealthEnum.HEALTHY,
		dependencies: [],
		createdAt: '2025-10-20T14:00:00Z',
		updatedAt: '2026-05-01T19:33:00Z',
	},
	{
		id: 'svc-search-indexer',
		projectId: 'proj-platform',
		ownerTeamId: 'team-platform',
		name: 'search-indexer',
		slug: 'search-indexer',
		description: 'Индексация каталога в OpenSearch',
		tags: ['worker', 'search'],
		language: 'Rust',
		repoUrl: 'https://github.com/devgate/search-indexer',
		pipelineUrl: 'https://ci.devgate.local/search-indexer',
		environments: [
			{ name: ServiceEnvironmentNameEnum.PROD },
			{ name: ServiceEnvironmentNameEnum.STAGE },
		],
		slo: { availability: 99.0 },
		health: ServiceHealthEnum.HEALTHY,
		dependencies: [],
		createdAt: '2025-12-01T09:00:00Z',
		updatedAt: '2026-04-15T13:22:00Z',
	},
	{
		id: 'svc-search-api',
		projectId: 'proj-platform',
		ownerTeamId: 'team-platform',
		name: 'search-api',
		slug: 'search-api',
		description: 'Публичный API поиска с фасетами',
		tags: ['api', 'search'],
		language: 'TypeScript',
		repoUrl: 'https://github.com/devgate/search-api',
		pipelineUrl: 'https://ci.devgate.local/search-api',
		environments: [
			{ name: ServiceEnvironmentNameEnum.PROD },
			{ name: ServiceEnvironmentNameEnum.STAGE },
		],
		slo: { availability: 99.5, latencyP95Ms: 220 },
		health: ServiceHealthEnum.HEALTHY,
		dependencies: ['svc-search-indexer'],
		createdAt: '2025-12-05T09:00:00Z',
		updatedAt: '2026-04-29T10:00:00Z',
	},
	{
		id: 'svc-cart-api',
		projectId: 'proj-commerce',
		ownerTeamId: 'team-commerce',
		name: 'cart-api',
		slug: 'cart-api',
		description: 'Управление корзинами пользователей',
		tags: ['api', 'orders'],
		language: 'TypeScript',
		repoUrl: 'https://github.com/devgate/cart-api',
		pipelineUrl: 'https://ci.devgate.local/cart-api',
		environments: [
			{ name: ServiceEnvironmentNameEnum.PROD },
			{ name: ServiceEnvironmentNameEnum.STAGE },
			{ name: ServiceEnvironmentNameEnum.DEV },
		],
		slo: { availability: 99.9, latencyP95Ms: 150 },
		health: ServiceHealthEnum.HEALTHY,
		dependencies: ['svc-auth-service'],
		createdAt: '2025-09-12T11:00:00Z',
		updatedAt: '2026-05-02T12:00:00Z',
	},
	{
		id: 'svc-shipping-tracker',
		projectId: 'proj-commerce',
		ownerTeamId: 'team-commerce',
		name: 'shipping-tracker',
		slug: 'shipping-tracker',
		description: 'Трекинг отгрузок, интеграция с провайдерами доставки',
		tags: ['worker', 'shipping'],
		language: 'Python',
		repoUrl: 'https://github.com/devgate/shipping-tracker',
		environments: [
			{ name: ServiceEnvironmentNameEnum.PROD },
			{ name: ServiceEnvironmentNameEnum.STAGE },
		],
		slo: { availability: 98.5 },
		health: ServiceHealthEnum.DEGRADED,
		dependencies: [],
		createdAt: '2025-11-10T15:00:00Z',
		updatedAt: '2026-05-03T08:00:00Z',
	},
	{
		id: 'svc-analytics-collector',
		projectId: 'proj-growth',
		ownerTeamId: 'team-growth',
		name: 'analytics-collector',
		slug: 'analytics-collector',
		description: 'Сбор клиентских событий в ClickHouse',
		tags: ['worker', 'analytics'],
		language: 'Go',
		repoUrl: 'https://github.com/devgate/analytics-collector',
		environments: [
			{ name: ServiceEnvironmentNameEnum.PROD },
			{ name: ServiceEnvironmentNameEnum.STAGE },
		],
		slo: { availability: 99.0 },
		health: ServiceHealthEnum.HEALTHY,
		dependencies: [],
		createdAt: '2025-08-25T10:00:00Z',
		updatedAt: '2026-04-22T14:00:00Z',
	},
	{
		id: 'svc-pricing-engine',
		projectId: 'proj-billing',
		ownerTeamId: 'team-billing',
		name: 'pricing-engine',
		slug: 'pricing-engine',
		description: 'Расчёт тарифов в реальном времени',
		tags: ['api', 'billing', 'critical'],
		language: 'Rust',
		repoUrl: 'https://github.com/devgate/pricing-engine',
		pipelineUrl: 'https://ci.devgate.local/pricing-engine',
		environments: [
			{ name: ServiceEnvironmentNameEnum.PROD },
			{ name: ServiceEnvironmentNameEnum.STAGE },
		],
		slo: { availability: 99.95, latencyP95Ms: 60 },
		health: ServiceHealthEnum.HEALTHY,
		dependencies: [],
		createdAt: '2025-07-30T09:00:00Z',
		updatedAt: '2026-05-01T16:00:00Z',
	},
	{
		id: 'svc-legacy-reports',
		projectId: 'proj-billing',
		ownerTeamId: 'team-billing',
		name: 'legacy-reports',
		slug: 'legacy-reports',
		description: 'Старая система отчётов, в процессе вывода из эксплуатации',
		tags: ['legacy', 'reports'],
		language: 'Python',
		repoUrl: 'https://github.com/devgate/legacy-reports',
		environments: [{ name: ServiceEnvironmentNameEnum.PROD }],
		health: ServiceHealthEnum.DOWN,
		dependencies: [],
		createdAt: '2024-03-15T10:00:00Z',
		updatedAt: '2026-04-10T12:00:00Z',
	},
];
