import {
	AuditAction,
	type AuditEventType,
	AuditTargetType,
} from '@/entities/audit-event';

export const MOCK_AUDIT_EVENTS: AuditEventType[] = [
	{
		id: 1,
		action: AuditAction.SERVICE_CREATED,
		actorId: 'usr-anna-ivanova',
		createdAt: '2026-05-03T10:42:00',
		payload: null,
		target: {
			id: 'svc-orders-worker',
			label: 'orders-worker',
			type: AuditTargetType.SERVICE,
		},
	},
	{
		id: 2,
		action: AuditAction.TEMPLATE_USED,
		actorId: 'usr-anna-ivanova',
		createdAt: '2026-05-03T10:39:00',
		payload: { newServiceId: 'svc-orders-worker' },
		target: {
			id: 'tpl-go-worker',
			label: 'Go Worker',
			type: AuditTargetType.TEMPLATE,
		},
	},
	{
		id: 3,
		action: AuditAction.ROLE_CHANGED,
		actorId: 'usr-alexey-zaytsev',
		createdAt: '2026-05-03T09:55:00',
		payload: { from: 'member', to: 'devops' },
		target: {
			id: 'usr-mikhail-orlov',
			label: 'Михаил Орлов',
			type: AuditTargetType.USER,
		},
	},
	{
		id: 4,
		action: AuditAction.SERVICE_UPDATED,
		actorId: 'usr-denis-kravtsov',
		createdAt: '2026-05-03T09:14:00',
		payload: { fields: 'pipelineUrl, docsUrl' },
		target: {
			id: 'svc-payments-api',
			label: 'payments-api',
			type: AuditTargetType.SERVICE,
		},
	},
	{
		id: 5,
		action: AuditAction.TEAM_MEMBER_ADDED,
		actorId: 'usr-anna-ivanova',
		createdAt: '2026-05-02T16:30:00',
		payload: { userId: 'usr-pavel-sidorov' },
		target: {
			id: 'team-platform',
			label: 'Platform',
			type: AuditTargetType.TEAM,
		},
	},
	{
		id: 6,
		action: AuditAction.INTEGRATION_CONNECTED,
		actorId: 'usr-alexey-zaytsev',
		createdAt: '2026-05-02T14:20:00',
		payload: null,
		target: {
			id: 'int-datadog',
			label: 'Datadog',
			type: AuditTargetType.INTEGRATION,
		},
	},
	{
		id: 7,
		action: AuditAction.SERVICE_DELETED,
		actorId: 'usr-roman-volkov',
		createdAt: '2026-05-02T11:05:00',
		payload: null,
		target: {
			id: 'svc-legacy-checkout',
			label: 'legacy-checkout',
			type: AuditTargetType.SERVICE,
		},
	},
	{
		id: 8,
		action: AuditAction.TEMPLATE_USED,
		actorId: 'usr-ekaterina-belova',
		createdAt: '2026-05-02T09:48:00',
		payload: { newServiceId: 'svc-promo-api' },
		target: {
			id: 'tpl-nodejs-service',
			label: 'Node.js Service',
			type: AuditTargetType.TEMPLATE,
		},
	},
	{
		id: 9,
		action: AuditAction.SERVICE_CREATED,
		actorId: 'usr-ekaterina-belova',
		createdAt: '2026-05-02T09:50:00',
		payload: null,
		target: {
			id: 'svc-promo-api',
			label: 'promo-api',
			type: AuditTargetType.SERVICE,
		},
	},
	{
		id: 10,
		action: AuditAction.ROLE_CHANGED,
		actorId: 'usr-alexey-zaytsev',
		createdAt: '2026-05-01T18:15:00',
		payload: { from: 'member', to: 'qa' },
		target: {
			id: 'usr-irina-fedorova',
			label: 'Ирина Фёдорова',
			type: AuditTargetType.USER,
		},
	},
	{
		id: 11,
		action: AuditAction.TEAM_MEMBER_REMOVED,
		actorId: 'usr-roman-volkov',
		createdAt: '2026-05-01T15:42:00',
		payload: { userId: 'usr-natalia-popova' },
		target: {
			id: 'team-commerce',
			label: 'Commerce',
			type: AuditTargetType.TEAM,
		},
	},
	{
		id: 12,
		action: AuditAction.SERVICE_UPDATED,
		actorId: 'usr-anna-ivanova',
		createdAt: '2026-05-01T13:08:00',
		payload: { fields: 'tags' },
		target: {
			id: 'svc-auth-service',
			label: 'auth-service',
			type: AuditTargetType.SERVICE,
		},
	},
	{
		id: 13,
		action: AuditAction.INTEGRATION_DISCONNECTED,
		actorId: 'usr-denis-kravtsov',
		createdAt: '2026-05-01T11:55:00',
		payload: null,
		target: {
			id: 'int-sonarqube',
			label: 'SonarQube',
			type: AuditTargetType.INTEGRATION,
		},
	},
	{
		id: 14,
		action: AuditAction.SERVICE_CREATED,
		actorId: 'usr-roman-volkov',
		createdAt: '2026-04-30T14:25:00',
		payload: null,
		target: {
			id: 'svc-analytics-pipeline',
			label: 'analytics-pipeline',
			type: AuditTargetType.SERVICE,
		},
	},
	{
		id: 15,
		action: AuditAction.TEMPLATE_USED,
		actorId: 'usr-roman-volkov',
		createdAt: '2026-04-30T10:32:00',
		payload: { newServiceId: 'svc-rates-grpc' },
		target: {
			id: 'tpl-rust-grpc',
			label: 'Rust gRPC Service',
			type: AuditTargetType.TEMPLATE,
		},
	},
	{
		id: 16,
		action: AuditAction.SERVICE_CREATED,
		actorId: 'usr-roman-volkov',
		createdAt: '2026-04-30T10:35:00',
		payload: null,
		target: {
			id: 'svc-rates-grpc',
			label: 'rates-grpc',
			type: AuditTargetType.SERVICE,
		},
	},
	{
		id: 17,
		action: AuditAction.ROLE_CHANGED,
		actorId: 'usr-alexey-zaytsev',
		createdAt: '2026-04-29T17:00:00',
		payload: { from: 'qa', to: 'member' },
		target: {
			id: 'usr-pavel-sidorov',
			label: 'Павел Сидоров',
			type: AuditTargetType.USER,
		},
	},
	{
		id: 18,
		action: AuditAction.SERVICE_UPDATED,
		actorId: 'usr-olga-petrova',
		createdAt: '2026-04-29T12:18:00',
		payload: { fields: 'docsUrl' },
		target: {
			id: 'svc-billing-gateway',
			label: 'billing-gateway',
			type: AuditTargetType.SERVICE,
		},
	},
	{
		id: 19,
		action: AuditAction.TEAM_MEMBER_ADDED,
		actorId: 'usr-irina-fedorova',
		createdAt: '2026-04-29T09:40:00',
		payload: { userId: 'usr-natalia-popova' },
		target: {
			id: 'team-growth',
			label: 'Growth',
			type: AuditTargetType.TEAM,
		},
	},
	{
		id: 20,
		action: AuditAction.SERVICE_DELETED,
		actorId: 'usr-anna-ivanova',
		createdAt: '2026-04-28T16:05:00',
		payload: null,
		target: {
			id: 'svc-trial-api',
			label: 'trial-api',
			type: AuditTargetType.SERVICE,
		},
	},
	{
		id: 21,
		action: AuditAction.INTEGRATION_CONNECTED,
		actorId: 'usr-denis-kravtsov',
		createdAt: '2026-04-28T11:32:00',
		payload: null,
		target: {
			id: 'int-slack',
			label: 'Slack',
			type: AuditTargetType.INTEGRATION,
		},
	},
	{
		id: 22,
		action: AuditAction.SERVICE_CREATED,
		actorId: 'usr-mikhail-orlov',
		createdAt: '2026-04-27T14:55:00',
		payload: null,
		target: {
			id: 'svc-search-api',
			label: 'search-api',
			type: AuditTargetType.SERVICE,
		},
	},
	{
		id: 23,
		action: AuditAction.TEMPLATE_USED,
		actorId: 'usr-mikhail-orlov',
		createdAt: '2026-04-27T14:50:00',
		payload: { newServiceId: 'svc-search-api' },
		target: {
			id: 'tpl-go-worker',
			label: 'Go Worker',
			type: AuditTargetType.TEMPLATE,
		},
	},
	{
		id: 24,
		action: AuditAction.SERVICE_UPDATED,
		actorId: 'usr-anna-ivanova',
		createdAt: '2026-04-26T09:18:00',
		payload: { fields: 'pipelineUrl' },
		target: {
			id: 'svc-orders-worker',
			label: 'orders-worker',
			type: AuditTargetType.SERVICE,
		},
	},
	{
		id: 25,
		action: AuditAction.ROLE_CHANGED,
		actorId: 'usr-alexey-zaytsev',
		createdAt: '2026-04-25T16:42:00',
		payload: { from: 'member', to: 'manager' },
		target: {
			id: 'usr-ekaterina-belova',
			label: 'Екатерина Белова',
			type: AuditTargetType.USER,
		},
	},
	{
		id: 26,
		action: AuditAction.TEAM_MEMBER_ADDED,
		actorId: 'usr-roman-volkov',
		createdAt: '2026-04-25T11:08:00',
		payload: { userId: 'usr-ekaterina-belova' },
		target: {
			id: 'team-commerce',
			label: 'Commerce',
			type: AuditTargetType.TEAM,
		},
	},
	{
		id: 27,
		action: AuditAction.SERVICE_CREATED,
		actorId: 'usr-olga-petrova',
		createdAt: '2026-04-24T13:30:00',
		payload: null,
		target: {
			id: 'svc-billing-gateway',
			label: 'billing-gateway',
			type: AuditTargetType.SERVICE,
		},
	},
	{
		id: 28,
		action: AuditAction.SERVICE_UPDATED,
		actorId: 'usr-roman-volkov',
		createdAt: '2026-04-23T15:14:00',
		payload: { fields: 'tags, docsUrl' },
		target: {
			id: 'svc-promo-api',
			label: 'promo-api',
			type: AuditTargetType.SERVICE,
		},
	},
	{
		id: 29,
		action: AuditAction.SERVICE_DELETED,
		actorId: 'usr-alexey-zaytsev',
		createdAt: '2026-04-23T10:00:00',
		payload: null,
		target: {
			id: 'svc-deprecated-feed',
			label: 'deprecated-feed',
			type: AuditTargetType.SERVICE,
		},
	},
	{
		id: 30,
		action: AuditAction.INTEGRATION_CONNECTED,
		actorId: 'usr-denis-kravtsov',
		createdAt: '2026-04-22T08:48:00',
		payload: null,
		target: {
			id: 'int-github',
			label: 'GitHub',
			type: AuditTargetType.INTEGRATION,
		},
	},
];
