export const HEADER_LABELS = {
	workspace: 'DevGate · Default',
	searchPlaceholder: 'Поиск сервисов, шаблонов, команд…',
	searchLabel: 'Глобальный поиск',
	notificationsAriaLabel: 'Уведомления',
	settingsAriaLabel: 'Настройки',
	sidebarExpand: 'Развернуть боковую панель',
	sidebarCollapse: 'Свернуть боковую панель',
	sidebarOpen: 'Открыть меню',
	sidebarClose: 'Закрыть меню',
	profileAriaLabel: 'Меню профиля',
	themeLight: 'Светлая тема',
	themeDark: 'Тёмная тема',
	menuTitle: 'Аккаунт',
	menuProfile: 'Профиль',
	menuLogout: 'Выйти',
} as const;
