export const SERVICE_DETAIL_LABELS = {
	tabOverview: 'Обзор',
	tabPipeline: 'Pipeline',
	tabDocs: 'Документация',
	tabDependencies: 'Зависимости',
	owner: 'Владелец',
	project: 'Проект',
	language: 'Язык',
	slo: 'SLO',
	updatedAt: 'Обновлён',
	createdAt: 'Создан',
	tagsTitle: 'Теги',
	environmentsTitle: 'Окружения',
	dependenciesTitle: 'Граф зависимостей',
	dependenciesEmpty:
		'У этого сервиса нет внешних зависимостей и обратных ссылок.',
	dependsOnTitle: 'Зависит от',
	dependsOnEmpty: 'Не зависит от других сервисов',
	usedByTitle: 'Используется в',
	usedByEmpty: 'На этот сервис никто не ссылается',
	dependencyGraphLegend: 'Стрелки идут в направлении вызова',
	docsTitle: 'Документация',
	docsEmpty: 'Документация ещё не привязана к сервису.',
	pipelineTitle: 'CI/CD пайплайн',
	pipelineEmpty: 'Пайплайн не привязан. Добавьте ссылку в карточке сервиса.',
	openRepo: 'Открыть репозиторий',
	openPipeline: 'Открыть pipeline',
	openDocs: 'Открыть документацию',
	openInEnv: 'Открыть',
	noEnvUrl: 'нет URL',
	notFoundTitle: 'Сервис не найден',
	notFoundDescription: 'Проверьте идентификатор или вернитесь в каталог.',
	backToCatalog: 'Вернуться в каталог',
	healthTitle: 'Здоровье',
	availabilityLabel: 'Доступность',
	latencyLabel: 'p95-задержка',
	noSloData: 'нет SLO-данных',
	healthyText: 'Сервис работает в штатном режиме.',
	degradedText: 'Зафиксирована деградация. Проверьте мониторинг.',
	downText: 'Сервис недоступен. Возможно идёт инцидент.',
	unknownText: 'Health-статус не отдан мониторингом.',
	activityTitle: 'Последние события',
	activityEmpty: 'По этому сервису событий пока нет.',
} as const;

export const SERVICE_DETAIL_TABS = {
	overview: 'overview',
	pipeline: 'pipeline',
	docs: 'docs',
	dependencies: 'dependencies',
} as const;

export const ENVIRONMENT_LABEL: Record<string, string> = {
	dev: 'dev',
	stage: 'stage',
	prod: 'production',
};
